[build]
  publish = "."

[[redirects]]
  from = "/thank-you"
  to = "/thank-you-static.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/static-complete.html"
  status = 200

# FormSubmit integration - same setup as RMT Solutions
# Emails sent directly to info@comfortlivingrealestate.com
# No configuration needed - zero setup required